### ISSUE TITLE
Update quick guide instructions

### ISSUE THREAD

**Issue by dtinth** [creatorsgarten/hacktoberfest-museum#22]
https://github.com/creatorsgarten/hacktoberfest-museum/blob/main/CONTRIBUTING.MD#quick-guide-to-add-your-project

Above instructions is outdated since this PR is merged:

- #13 

Please update the instructions accordingly.

**Comment by ryanrw** [comment]
@dtinth I already added some instruction about `pnpm`. But I think we also need some more further update krub.

**Comment by intaniger** [comment]
updated `Quick guide to add your project`: https://github.com/creatorsgarten/hacktoberfest-museum/pull/31
