### ISSUE TITLE
Add git hook for run prettier after commit something

### ISSUE THREAD

**Issue by ryanrw** [creatorsgarten/hacktoberfest-museum#28]
I saw a lot of PRs failed for CI checking because prettier, so I think we should add some prettier write (or something else e.g. [pretty-quick](https://www.npmjs.com/package/pretty-quick)) to format the codebase before open any PR.

**Comment by Leomotors** [comment]
:+1:

**Comment by new5558** [comment]
@Gusb3ll Should I start doing PR for this? per #36 dicussion

**Comment by Gusb3ll** [comment]
> @Gusb3ll Should I start doing PR for this? per #36 dicussion

That would be greatly appreciated :pray: 🥇
